# Hexo Configuration
## Docs: http://zespia.tw/hexo/docs/configure.html
## Source: https://github.com/tommy351/hexo/


# Site #整站的基本信息
title: Network-Tech                 #网站标题
subtitle: "about Network Tech "     #网站副标题
description: wwyyzz blog | network | Wireshark | Docker | Hexo        #网站描述，给搜索引擎用的，在生成html中的head->meta中可看到
author: wwyyzz                      #作者，左下角显示
email: sdn_app@163.com
language: zh-cn                     #语言
timezone: UTC

# URL #域名和文件结构
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://wwyyzz.github.io
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code

#archive_dir: Blog
#code_dir: downloads/code

# Writing 文章布局、写作格式的定义
new_post_name: :title.md             # File name of new posts
default_layout: post                 #默认layout方式
auto_spacing: false                  # Add spaces between asian characters and western characters
titlecase: false                     # Transform title into titlecase
external_link: true                  # Open external links in new tab
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: true
highlight:                          #代码高亮
  enable: true                      #是否启用
  line_number: false                #是否显示行号
per_page: 0


# Category & Tag                   #分类与标签
default_category: uncategorized
category_map:
tag_map:

# Archives 默认值为2，这里都修改为1，相应页面就只会列出标题，而非全文
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 1

# Server #本地服务参数
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: true
logger_format:

# Date / Time format #日期显示格式
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination #分页设置
## Set per_page to 0 to disable pagination
per_page: 10                      #每页10篇文章
pagination_dir: page


# Extensions 这里配置站点所用主题和插件
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes
theme: navy


# Deployment 站点部署到github要配置
## Docs: http://zespia.tw/hexo/docs/deploy.html
deploy:
  type: git
  repository: git@github.com:wwyyzz/wwyyzz.github.com.git 

#duoshuo_shortname: wwyyzz
twitter: navy9449
github: wwyyzz
